language: php
php:
- 5.6
before_script:
- composer update --no-dev
after_success:
- npm install gulp
- npm update
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - secure: JM6uLpqahh3yF9vKh0NioP0NkAvfvwC22ET1y5WN+6sYTzjKhAiCHORZKkcNRWCgKb0yUaz823MQmJnGC1X5ZhGeXBCo+kgMsqVwiW8lSj555O/dfYbEx1EXJSx0vgkOGp5/Uo0SjLnImvriKNKcXJYqNH8b7YT3EZEiCWw3VLJBMLE9617UJIDp+V/jDPuGgiG97ASze+kyaXkSmzVuUTtC/hj80oqOIDJjnoNsn0rXMPyUrzW71ecnZ60qr8lykbsLaN7FVbtWscmJo3hfVcbBuCffx2lU1Dv347beBSVPyLEjNsaQa+5DgGZvqcgIsJuolj2WMM8q6ZX+oCQiMKLfRn0+HI3TgJzBe4MVOq9xvMY7s87JIRArr7a3cCbNYdPC0BN3zDRVkPzp5/hEI/qq0UUt6qSN5TnVS4p52MN1KuXL4Fh+hLICjvg9LWeHlA+EvqbtPtgM+3AyV6J7p3+MXMGhbDLauSxVf5ObnHHOO6af3N3VTZ3Jqh7bzJSvTBd6IWrlbx+xIrfO5x8DP51K00wd3yMCMWH8nYrYY8Ts9myMKB5G4Q3D8Q3hfTF9zjOUNUBLWVEPQdR3IprlCsGeUBzXSSHVgrCOgEVLWrWvX6AtADmHhixA1lG9CTLiDgHQHuaUt2oi8raWUJG1yNKtttiB5ROssZGTDwjoJNI=
  - secure: ft0Os17gt+r7lSamywvF3TKaOWj1aXPDDaOf63VYawSe2DEKXkGIM2alP635GAv2kp4ASpMCDLrzWfyNOngvQiIJWwC9GUCbQ7gAxfIOLhsYT8hINxD6ENSRNRMdNzhGSDnBnBol7hoUEYFo9h2qf/fEraOECDKZFJHPMgDC/eqmxAbyXxdhHO5df1pQpWTPG5fVVgTBjDTDaNjdwTWWT9x+X2jWJOngTZeZi5KvUvqJDhPA3jYec3zkPtEM5XCoI6USMLT2srWn8or7CqSVE3cBz4Uzl5eD7NNB2KdrV8XMNGxbN8+GAk5OGZUrc39mJn18PldG5K6DLEDNHhelPjV+E8OuQ0Gd5r/fQwEthlWjY1MvOTe+JBP1Ri/M99G+pmUe6JopxIU/V2y9wM7pixuXpl3CusyMEK805gmUXy2XF7iAAtnb1efVBoYPMtz+QdfNXps/Q7BYr3KAH8QiBSzQPc/yFDE5rGwlez13DDGu/Zj++7yuUFR0D/m9KxzS+IpaqLk+niq3WRVzPUoJ1LERBqHUrj1EfmcCYNvL98VCskWt2Z0yAS3JqyNNDQjXvbZYsSEVebxWUw0Gzo1hjWfEvbQu7hKblJrC39oq2TAC0JIpNEen5jCnuSpu2iRJA939KlB0Jo0lcHcICRn8q3lW36Lw0TYSqjkZ/OcWa0c=
