language: php
php:
- 5.6
before_script:
- composer update --no-dev
after_success: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - secure: Xx89/0YZFmLCc1bd9tVLoMh1cpu/Jefl0Nq7KsN5m1gT9cQT5BPUyavdt9j9muxHKNAKd2wFfpKLPHwhQd5o0vN3vuqUSM8XzD88lKDfjY/mirJmFHGZe31DT48zqjrMbrKRMQs3HV6czicC7hZq1vjAvilEXPX4fkoLSyhKJddaljiad9RpNo/+8rVUL6NJTcHRrt2cavkjY57DFuk4+yWYRwyBQkRVrRwIKOGSucFarm0zWA3T8QH1uplh8jCehb+U/yh/FTIWQcP+pTmGQCAofQC9/8JhD0B78gN6coP6JNyuCpfuaGev/kSmt+U3uqwrdJmmtVtPK0WL2DC7ssNmFM8MZmu/CwkgPRIWp2u6jlZCfA0Q35DtdZErNxXYCatBkNl3XXLFsma1BPMdmwiRfLnc/FMegm6w6vXMIfq8gsUOGEOcqyBzHRfYeQ6mdYctipGCt5Hazv59EqSdOVfZo1gyHjWYJvz5Y5o5U8ExXkHTkthb/B+4t2qn77EvkciihUs60we1Nu+Omq+vo0kUckTacWGb+zfVi+23fcdGrsSCMwmwwvwFfBVd+syKwPShh7JiqiR9xCk2wEToNJROuZrxBgrb2SmPisN/CIll5fQFOsnuNiX039Ej2UWf6Vmr1FtcVO+2kFuliN7ltbhSWVfCyqiBm43rrbBk9+w=
  - secure: hXdotgueLi1ajd2j7fg2R9+uljwFXMSZB9CWSAPLucEGiCtmv6bj9JXSYHo+cuGYTHe7P4oX5eEI8wTkepn9X7CaFgj/bHVK86x3GAWIoZFkvotl132TrJg7EdlRO886pG7nQZszoncz8ytYjVNlGmumjD3T4UQ0WEgS6dkKMRYzuHSkG3I1faZjgob/WvIvhDTf2oxiPfwq8WcSpHz5UUp3sm8G0s1R8rlUWs4rTXJIEs0ek+tNd4bKXpbcTgh893R9utCPYTAQqa9zl839Koz+j7fLEVYapU1I5AlcAD1Kprlo09K0SEnS//Bv5//pt1lVW6EWuRZ8zuGypzO3zliyYLAvX24hx/1mvprUi/7z7VrFx7/4OGDGYn6FIYTuop63fp2Eu6WU4bWBi8wx6fgFr6YLZLTgUX8g/6FBIrj7MegteG7gescVoxHxJp4eqEGcquFawQAIXrxJWhhWpICcGiLJxqJKBuYgvwLF+KkqKoxgB2+WTvhtvTM1sXXAnFlMi8ARbunZMFGes/xGVbH0fwtFX/I2aJrUVVDxms958nkdm4Vv4oMH+3GO8ViUstBKl/JJdVg/HzcJFFq9baKl/wwZnXpar4eMjMXZKEOWhruu21nSfFubPzsxPYbXSFDD36/N93qDtehgsMcJdKOoiorscjwM+M9lVCO2Zkc=
